title: "Mustafa Morca"

description: "Portfolio showcasing blockchain, smart contracts, and AI projects."

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: auto
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/psychoplasma"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/mustafa-morca-a2472931/"